Работа с условиями
htmlacademy-php/1842585-readme-12 pull request #2
Opened 2021-08-12 07:01 UTC by artidy

2021-08-13 04:31 UTC, mihan007 requested changes
Отличный старт! Есть предложения к улучшению, изучи, пожалуйста.

2021-08-13 04:31 UTC, mihan007 commented on index.php
> +            <?php if ($is_auth): ?>
Сразу внедрим практику форматирования кода по промышленному стандарту PSR-12. Посмотри https://mihan007.notion.site/PSR-12-Code-Style-f23d1acfbd5e446f8837aed0c4669e63

В частности здесь надо внутри условия сделать отступ всем внутренним кодом, чтобы было видно иерархию.

2021-08-13 04:41 UTC, artidy commented on index.php
> +            <?php if ($is_auth): ?>
А как мне настроить это на visual studio code?

2021-08-13 11:32 UTC, mihan007 commented on index.php
> +            <?php if ($is_auth): ?>
https://marketplace.visualstudio.com/items?itemName=ikappas.phpcs + https://guides.hexlet.io/vscode-for-php-setup/

2021-08-13 11:33 UTC, mihan007 commented on index.php
> +            <?php if ($is_auth): ?>
@artidy у меня есть купон на 4 месяца PhpStorm для обучения. JetBrains выдали. Рекомендую на него перейти - лучше ничего нет.

2021-08-13 11:33 UTC, mihan007 commented on index.php
> +            <?php if ($is_auth): ?>
За купоном - пиши, поделюсь

2021-08-14 04:52 UTC, mihan007 requested changes
Ура! Мы двигаемся вперед!

Сейчас отладим стандарты кодирования и дальше пойдет быстрее.

2021-08-14 04:52 UTC, mihan007 commented on index.php
> +            <?php
Есть подозрение, что в твоем редакторе кода стоит насильный перенос после тега <?php. Это не подходит для файлов шаблонов. Изучи, пожалуйста, https://mihan007.notion.site/PSR-12-Code-Style-f23d1acfbd5e446f8837aed0c4669e63

В данном случае я ожидаю `<?php if ($is_auth): ?>` на одной строке как и аналогичные конструкции в шаблонах

2021-08-14 04:52 UTC, mihan007 commented on index.php
> +            endif; ?>
И здесь на одной строке

2021-08-14 04:53 UTC, mihan007 commented on index.php
> +            <?php if ($is_auth): ?>
Я понял, что повторяюсь с PSR-12 :) Что ж - повторение мать учения. Я дополнил документ - посмотри, пожалуйста

2021-08-14 06:51 UTC, mihan007 approved these changes
Perfecto!🤗

2021-08-14 06:51 UTC, merged