iteration of array
htmlacademy-php/1842585-readme-12 pull request #3
Opened 2021-08-14 18:28 UTC by artidy

2021-08-15 04:39 UTC, mihan007 requested changes
Очень хорошо разобрался в теме. Предлагаю упростить шаблон. Ты же помнишь принципы хорошего разработчика?
1. Программирование - это управление сложностью. Меньше сложность - лучше поддержка и любовь команды
2. KISS - Keep it simple and stupid

2021-08-15 04:39 UTC, mihan007 commented on index.php
> +                        <?php if ($post["type"] === "post-quote"): ?>
1. тут лучше подойдет switch или match https://www.php.net/manual/ru/control-structures.match.php
2. шаблон выходит очень громоздким, вынеси каждый блок с выводом определенного вида контента, в отдельный шаблон. это даст более легкую поддержку и ясность намерений в главном шаблоне. у тебя будет что-то вроде `templates/post/post_quote.php`, `templates/post/post_link.php` и так далее

2021-08-16 05:17 UTC, mihan007 requested changes
Все правильно сделал. Есть небольшие предложения по улучшению. Из серьезного - доработка case, которая убережет тебя и код от ошибочных входных данных и код "упадет", когда это будет нужно, вместо вывода некорректной информации.

Сценарий "упадет" это отличный вариант. Надо знать про другой. Возможно, если тип поста неизвестен системе, то его можно просто не выводить. Это должно быть прописано в ТЗ. Я этот вариант не рекомендую. Называется "замести сор под половик". Лучше - упасть, увидеть ошибку и исправить. Чем пользователь будет сидеть и втыкать - пост сохранился, но не показывается

2021-08-16 05:17 UTC, mihan007 commented on index.php
> +                            default:
лучше явно прописать `case "post-text"`, а в ветке default прервать выполнение через `die("Неизвестный тип поста")`. это убережет программу от некорректной работы, если добавится новый тип post или ошибутся в названии существующего типа post

2021-08-16 05:17 UTC, mihan007 commented on templates/post/post_link.php
> +    <a class="post-link__external" href="http://<?= $post["contain"] ?>"
1. `href="http://<?= $post["contain"] ?>"` => я бы не стал так делать. лучше http:// унести в массив и здесь просто выводить `$post["contain"]`. очень вероятно, что так как сделано сейчас выдаст http://https://image.com, если входные данные начнут сохранять полный url
2. да и может быть в информации о посте будет https? на уровне вывода это уже не угадаешь. поэтому держим полный url в теле поста

2021-08-16 05:17 UTC, mihan007 commented on templates/post/post_photo.php
> +    <img src="img/<?= $post["contain"] ?>" alt="Фото от пользователя" width="360"
В alt записывают информацию о сообщении. Тут подойдет `$post["title"]`

2021-08-16 05:17 UTC, mihan007 commented on templates/post/post_quote.php
> +    <cite>Неизвестный Автор</cite>
Может быть `$post["user_name"]`? Я не уверен.

2021-08-16 05:17 UTC, mihan007 commented on templates/post/post_video.php
> +        <img src="img/coast-medium.jpg" alt="Превью к видео" width="360" height="188">
я бы в alt сделал расширенное описание. Оставил "Превью к видео" и после него вставил $post["title"]. То есть "Превью к видео котики весело играют на улице"

2021-08-16 06:54 UTC, artidy commented on templates/post/post_quote.php
> +    <cite>Неизвестный Автор</cite>
Тут не обязательно пользователь создавший пост является автором цитаты, и поле не предусмотрено такое.

2021-08-25 04:55 UTC, mihan007 approved these changes
Fint!

2021-08-25 04:55 UTC, merged