create templates layout and main
htmlacademy-php/1842585-readme-12 pull request #5
Opened 2021-09-04 06:15 UTC by artidy

2021-09-07 08:54 UTC, mihan007 requested changes

2021-09-07 08:54 UTC, mihan007 commented on functions.php
> +    return [
интересное решение

2021-09-07 08:54 UTC, mihan007 commented on templates/layout.php
> +    <?php print($main); ?>
Посмотри на `<?= $main ?>`, будет лаконичнее

2021-09-07 08:54 UTC, mihan007 commented on templates/main.php
> + * @var $posts array - массив постов пользователей
посмотри на ArrayShape в PhpStorm. Это способ детальнее описать, что будет в массиве. В частности ключи. Такое описание дает возможность IDE подсказывать тебе в шаблоне намного лучше. Очень удобно

2021-09-07 08:54 UTC, mihan007 commented on templates/main.php
> +            <article class="popular__post post <?= $post["type"] ?>">
я рекомендую тело цикла также вынести в отдельный файл. сейчас начало foreach сильно отделено от завершения и сложно вспомнить в конце, что его надо поставить. попробуем упростить?

2021-09-07 08:54 UTC, mihan007 commented on templates/main.php
> +                            require("./templates/post/post_quote.php");
шикарное решение!

2021-09-07 08:54 UTC, mihan007 commented on templates/post/post_link.php
> + * @var $post array
ArrayShape

2021-09-07 08:54 UTC, mihan007 commented on templates/main.php
> +                    <h2><?= $post["title"] ?></h2>
экранируем данные. они же от пользователя пришли и может быть дичь и уязвимость

2021-09-07 08:54 UTC, mihan007 commented on templates/post/post_link.php
> +                <h3><?= htmlspecialchars($post["title"]) ?></h3>
экранировал - отлично!

2021-09-07 08:54 UTC, mihan007 commented on templates/post/post_photo.php
> + * @var $post array
ArrayShape

2021-09-07 08:54 UTC, mihan007 commented on templates/post/post_quote.php
> + * @var $post array
ArrayShape

2021-09-07 08:54 UTC, mihan007 commented on templates/post/post_text.php
> + * @var $post array
ArrayShape

2021-09-07 08:54 UTC, mihan007 commented on templates/post/post_text.php
> +<?php if ($postSettings["truncated"]): ?>
прям отлично

2021-09-07 08:54 UTC, mihan007 commented on functions.php
> +function truncateContent(string $content, int $maxLength = 300): array
идеальная функция!

2021-09-12 06:29 UTC, ademaro approved these changes
Давай пока закрою, двигаем дальше, но жду на консультацию, что бы привести в порядок проект, что бы спокойно развивать дальше

2021-09-12 06:29 UTC, ademaro commented on templates/layout-post.php
> +        <h2><?= $post["title"] ?></h2>
htmlspecialchars или strip_tags добавляем для вывода в шаблонах, что бы не было XSS уязвимостей

2021-09-12 06:29 UTC, ademaro commented on templates/layout-post.php
> +                require("./templates/post/post_quote.php");
require? у нас же есть функция рендера шаблонов, почему не через неё? Плюс можно подумать более универсально этот момент, много повторений одного и того же, что думаешь?

2021-09-12 06:29 UTC, ademaro commented on templates/main.php
> +        }
это вынести в контроллер так же, куски разметки (подшаблонов) через include_template() давай сделаем. Почитай про MVC, предлагаю созвониться и разобрать всё детальнее в плане архитектуры проекта и в целом по мелочам заодно пройдёмся.

2021-09-12 06:36 UTC, merged

2021-09-23 14:24 UTC, ro-htmlacademy commented on functions.php
> + * result = ["content" => "Американский драматический сериал в жанре фэнтези, является адаптацией цикла романов
Длина предложения "Американский драматический сериал в жанре фэнтези, является адаптацией цикла романов «Песнь Льда и Пламени». Создатели сериала — сценаристы Дэвид Беньофф и Дэн Вайс, съёмки ведутся в Северной Ирландии, Хорватии, Исландии, Испании, Марокко" *значительно* меньше 400 символов.