Создал файл schema.sql и описал создание бд и таблиц
htmlacademy-php/1842585-readme-12 pull request #7
Opened 2021-09-25 13:58 UTC by artidy

2021-09-25 15:58 UTC, ro-htmlacademy commented
Структура таблиц идеальная, я только рекомендую убрать поля типа char.
Их имеет смысл использовать только в очень специфических случаях и только если вся таблица состоит из полей фиксированной длины.

Из недочётов я бы отметил что не выполнен пункт 3 в разделе План работы 

По каждому внешнему ключу я бы хотел видеть небольшую "защиту" - почему ключ используется для данного поля и почему выбрано именно такое действие.

2021-09-26 11:26 UTC, ro-htmlacademy commented
Я думаю, что запрет удаления для некоторых таблиц - не самое лучшее действие.
Для некоторых лучше подойдёт удаление связанных записей, как вы и хотели ранее.

И снова напоминаю про уникальные поля.

2021-09-26 17:59 UTC, zenoleg requested changes

2021-09-26 17:59 UTC, zenoleg commented on schema.sql
> +  registered DATETIME            NOT NULL,
Я бы советовал временные столбцы именовать с постфиксом _at

Пример: created_at, visited_at...
Иначе ощущение, что это булевое значение, пока не видишь тип данных

2021-09-26 17:59 UTC, zenoleg commented on schema.sql
> +  email      VARCHAR(128) UNIQUE NOT NULL,
Мы можем потерять пользователей с email длиннее 128 символов. 
В RFC указано максимум 320 символов включая домен почтового ящика. 

https://www.rfc-editor.org/errata_search.php?eid=1690#:~:text=It%20should%20say%3A-,In%20addition%20to%20restrictions%20on%20syntax%2C%20there%20is%20a%20length,total%20length%20of%20320%20characters.

> In addition to restrictions on syntax, there is a length limit on
>    email addresses.  That limit is a maximum of 64 characters (octets)
>    in the "local part" (before the "@") and a maximum of 255 characters
>    (octets) in the domain part (after the "@") for a total length of 320
>    characters.

2021-09-26 17:59 UTC, zenoleg commented on schema.sql
> +  password   VARCHAR(64)         NOT NULL,
По длине пароля пока можем оставить так, но в дальнейшем мы будем хешировать пароль, чтобы не хранить в открытом виде. К тому моменту скорее всего придется изменить длину столбца.

2021-09-26 17:59 UTC, zenoleg commented on schema.sql
> +  created     DATETIME     NOT NULL,
Лучше добавить постфикс _at

2021-09-26 17:59 UTC, zenoleg commented on schema.sql
> +  avatar     VARCHAR(125)
Здесь лучше тоже уточнить, что за avatar?  ID во внешней БД или путь на сервере?
Как тебе `avatar_path`?

2021-09-26 17:59 UTC, zenoleg commented on schema.sql
> +  views_count INT DEFAULT 0,
Для счетчика нам не нужна отрицательная часть инта, поэтому лучше сразу использовать UNSIGNED

```suggestion
  views_count INT UNSIGNED DEFAULT 0,
```

2021-09-26 17:59 UTC, zenoleg commented on schema.sql
> +  created DATETIME     NOT NULL,
Не забываем за постфикс `_at`

2021-09-26 17:59 UTC, zenoleg commented on schema.sql
> +  created      DATETIME      NOT NULL,
Не забываем постфикс `_at` :)

2021-09-26 17:59 UTC, zenoleg commented on functions.php
> +        $date_count = ceil($diff->days / 7);
👍

2021-09-26 17:59 UTC, zenoleg commented on schema.sql
> +  picture     VARCHAR(125),
Давай тут уточним, что именно здесь лежит. 
Например, `picture_url`

2021-09-26 17:59 UTC, zenoleg commented on schema.sql
> +  video       VARCHAR(125),
Здесь тоже можно уточнить, что именно лежит. 
`video_url`?

2021-09-26 18:01 UTC, zenoleg commented on schema.sql
> +  login      VARCHAR(128)        NOT NULL,
Логин в системе должен быть так же уникален

2021-09-27 07:57 UTC, merged