Добавил файл подключения к базе данных db.php, выполнил запрос постов…
htmlacademy-php/1842585-readme-12 pull request #9
Opened 2021-09-29 15:59 UTC by artidy

… из базы данных

2021-09-29 18:22 UTC, zenoleg requested changes

2021-09-29 18:22 UTC, zenoleg commented on db.php
> +<?php
Будет в дальнейшем неудобство, что при любом подключении db.php будут сразу же идти селекты в БД.
Предлагаю в этом файле инициировать подключение и инкапсулировать логику получения данных из БД в функции.

`function fetchPosts(int $limit)`
`function fetchPostTypes(int $limit)`

2021-09-29 18:22 UTC, zenoleg commented on db.php
> +<?php
И в index.php уже дернуть функции и заполнить нужные массивы данных

2021-09-29 18:22 UTC, zenoleg commented on db.php
> +<?php
Так же советую сделать так, чтобы ты сам заполнял массивы данных, вроде

`return ['name' =>$line['name'], 'class' => $line['class']];`

Иначе, если изменится название какой-либо колонки -- то придется везде искать и менять название, а так только в одном месте. 

Наша бизнес логика не должна сильно зависеть от инфраструктуры (База данных)

2021-09-29 18:22 UTC, zenoleg commented on db.php
> +    print("Ошибка подключения: " . mysqli_connect_error());
Я думаю, что в нашем случае можно полностью останавливать приложение с помощью функции die()
И в нее уже положить сообщение
die("Ошибка подключения: " . mysqli_connect_error())

2021-09-29 18:22 UTC, zenoleg commented on db.php
> +    print("Ошибка подключения: " . mysqli_connect_error());
Смысла сообщения сверху верстки особо не вижу, для обучения и упрощения кода можем сделать именно так

2021-09-29 18:22 UTC, zenoleg commented on db.php
> +    $query = "SELECT name, icon_class from content_types";
Для глаза слишком много ветвлений if else.
Как хорошую практику, советую максимально уходить от else. 

Здесь это можно решить таким способом:

```suggestion
if ($connect === false) {
    die("Ошибка подключения: " . mysqli_connect_error());
}
$query = "SELECT name, icon_class from content_types";
// и так далее
```

2021-09-29 18:22 UTC, zenoleg commented on db.php
> +           CONCAT('post-', content_types.icon_class) as type,
Хорошее решение с CONCAT, но лучше логику верстки или бизнес логику не переносить на базу данных.
Лучше конкатенацию делать на уровне шаблона

2021-09-29 18:22 UTC, zenoleg commented on index.php
> +    "post_types" => $post_types,
Здесь будет явный вызов твоей функции для получения выборки. Иначе непонятно, откуда взялась переменная `$post_types`.
Нужно писать код, чтобы его можно было сразу же понять, без магических переменных.

2021-09-29 18:22 UTC, zenoleg commented on templates/main.php
>   * @var $posts array<array{title: string, type: string, contain: string, user_name: string, avatar: string}> - массив постов пользователей
Отличный PHPDOC со всеми ключами!
Этого даже мидлы почти не делают, офигенно!

2021-09-29 18:22 UTC, zenoleg commented on templates/main.php
> +                <?php foreach ($post_types as $post_type): ?>
По-моему ты забыл вывести сами посты из БД

2021-09-29 18:29 UTC, zenoleg commented on db.php
> +    if ($result == false) {
В идеале никогда не использовать сравнения без учета типов `==`, оно может породить некрасивые баги.
Делаем всегда сравнение через `===`

http://sandbox.onlinephpfunctions.com/code/2f9653a20640ec184053a1cc76c6c18b86b344cc

2021-10-03 05:10 UTC, artidy commented on templates/main.php
> +                <?php foreach ($post_types as $post_type): ?>
Я не забыл, они и до этого выводились, я просто поменял массив в файле на массив из запроса бд.

2021-10-03 05:11 UTC, artidy commented on db.php
> +<?php
> Так же советую сделать так, чтобы ты сам заполнял массивы данных, вроде
> 
> `return ['name' =>$line['name'], 'class' => $line['class']];`
> 
> Иначе, если изменится название какой-либо колонки -- то придется везде искать и менять название, а так только в одном месте.
> 
> Наша бизнес логика не должна сильно зависеть от инфраструктуры (База данных)

Не совсем понял, что тут сделать надо?

2021-10-03 09:17 UTC, zenoleg commented on db.php
> +<?php
Идея в том, чтобы ты полученные данные обработал под своими именами.
Демо: http://sandbox.onlinephpfunctions.com/code/75345e22528aa73ad03ecf5d86af17629f18e8ce

Тем самым не тащишь snake_case нейминг из базы в код, плюс контроль ключей массивов в одном месте.

Без этого, при изменении столбца `name` на `title`, ты будешь бегать по всему коду делать замену

2021-10-03 09:17 UTC, zenoleg commented on templates/main.php
> +                <?php foreach ($post_types as $post_type): ?>
Хорошо, извини, не заметил)

2021-10-03 09:23 UTC, zenoleg commented on db.php
> +        return [];
Функция die() прерывает исполнение всего кода, до return [] исполнение не дойдет.

2021-10-03 09:23 UTC, zenoleg commented on db.php
> +    return fetchData($queryPopularPosts);
Как рекомендация по код стайлу -- делай отступы между логическими блоками.

```suggestion
    LIMIT 6";
    
    return fetchData($queryPopularPosts);
```

2021-10-03 09:23 UTC, zenoleg commented on db.php
> +    return fetchData($queryPopularPosts);
И так везде)
Иначе читается плохо

2021-10-03 09:23 UTC, zenoleg commented on functions.php
> +        $type_key = array_search($post["type_id"], array_column($post_types, "id"));
Отлично, что используешь array_search и array_column

2021-10-03 09:23 UTC, zenoleg commented on index.php
> +$post_types = fetchPostTypes();
Переменные излишни, можно сразу присваивать нужным ключам для вывода в шаблон

2021-10-03 13:28 UTC, merged